name: secondchance
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  models:
    path: ./modules/models
  common_dependencies:
    path: ./modules/common_dependencies
  ui_common:
    path: ./modules/ui/ui_common
  ui_lobby:
    path: ./modules/ui/ui_lobby
  ui_login:
    path: ./modules/ui/ui_login

  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/logo.png"
  min_sdk_android: 21

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/png/

