name: ui_lobby
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  common_dependencies:
    path: ../../common_dependencies

  models:
    path: ../../models
  ui_common:
    path: ../ui_common

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
